### PR TITLE
refactor: rename

### PR DESCRIPTION
**Pull request by zizhong**

### CODE REVIEW

**Review by chester-leung — APPROVED** [review]

**Comment by chester-leung** [comment]
@zizhong let me fix the RTD issue

**Review by chester-leung — CHANGES_REQUESTED** [review]
@zizhong can we make the Parameters list [here](https://github.com/opaque-systems/promptguard-python/blob/9f848934fa872c3e274bb5287a0309175482ca4a/python-package/src/opaqueprompts/opaqueprompts_service.py#L55) match the function signature?

**Comment by chester-leung** [comment]
> @zizhong can we make the Parameters list [here](https://github.com/opaque-systems/promptguard-python/blob/9f848934fa872c3e274bb5287a0309175482ca4a/python-package/src/opaqueprompts/opaqueprompts_service.py#L55) match the function signature?

Actually, I'll fix it

**Comment by zizhong** [comment]
@chester-leung Thanks!

**Review by chester-leung — APPROVED** [review]
If CI passes, LGTM

**Pull request merged**
